# 
# Do not Edit! Generated by:
# spectacle version 0.15
# 
# >> macros
# << macros

Name:       uim
Summary:    User Mode Initialization Manager
Version:    0.1
Release:    1
Group:      System/Daemons
License:    GPLv2+
URL:        http://dev.omapzoom.org
Source0:    uim.tgz

%description
User Mode Init manager - For TI shared transport drivers    




%prep
%setup -q -n %{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
%{_bindir}/uim
# >> files
# << files


